dist: xenial
addons:
  apt:
    packages:
      - xcftools
      - libpng16-16
      - webp
sudo: required
language: node_js
node_js:
- "11"
install:
- rm package-lock.json && make node_modules
script:
- make
